version: '3.1'

services:
  web:
    image: "drupal"
    ports:
      - "8081:80"
    volumes:
      - ./data/files:/var/www/html/sites/default/files
    networks:
      - internal

  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal8
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - internal

  dbadmin:
    image: "phpmyadmin/phpmyadmin"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8082:80"
    networks:
      - internal

networks:
  internal:
